//! Skills
export const SKILLS = [
  {
    title: "Frontend",
    icon: "/assets/frontend.png",
    skills: ["HTML", "CSS", "jQuery", "React Js"],
    techIcons: [
      "/assets/techImg/html.svg",
      "/assets/techImg/css.svg",
      "/assets/techImg/jquery.svg",
      "/assets/techImg/react.svg",
    ],
  },
  {
    title: "Backend",
    icon: "/assets/backend.png",
    skills: ["PHP", "MySQL", "nodeJs", "mongoDB"],
    techIcons: [
      "/assets/techImg/php.svg",
      "/assets/techImg/mysql.svg",
      "/assets/techImg/nodejs.svg",
      "/assets/techImg/mongodb.svg",
    ],
  },
  {
    title: "Tools",
    icon: "/assets/tools.png",
    skills: ["Git & GitHub", "VS Code"],
    techIcons: ["/assets/techImg/github.svg", "/assets/techImg/vs code.svg"],
  },
  {
    title: "UI/UX",
    icon: "/assets/ui_ux.png",
    skills: ["Figma"],
    techIcons: ["/assets/techImg/figma.svg"],
  },
];

//! Projects
export const PROJECTS = [
  {
    title: "Currency Convertor - Convert currency based on latest price",
    projectImg: ["/assets/Currency/image1.png"],
    video: "https://drive.google.com/file/d/1Vc1bV8esaEpJW0jMeybrISgwkIQEOnFA/preview",
    url: "https://currency-convertor-ten-taupe.vercel.app/",
    source: "https://github.com/Makwana-Dainik-Kalabhai/Currency-Convertor",
    skills: ["HTML", "CSS", "jQuery"],
    tech: "FrontEnd",
    techIcons: [
      "/assets/techImg/html.svg",
      "/assets/techImg/css.svg",
      "/assets/techImg/jquery.svg",
    ],
  },
  {
    title: "Dots and Boxes - Play game via drawing lines between dots",
    projectImg: [
      "/assets/DotBoxes/image1.png",
      "/assets/DotBoxes/image2.png",
      "/assets/DotBoxes/image3.png",
      "/assets/DotBoxes/image4.png",
    ],
    video: "https://drive.google.com/file/d/1ESnn1w5IRE2zRBr6Vz2Tf-NbaxAJrmAs/preview",
    url: "https://dots-and-boxes-blush.vercel.app/",
    source: "https://github.com/Makwana-Dainik-Kalabhai/DotsAndBoxes",
    skills: ["HTML", "CSS", "Javascript"],
    tech: "FrontEnd",
    techIcons: [
      "/assets/techImg/html.svg",
      "/assets/techImg/css.svg",
      "/assets/techImg/jquery.svg",
    ],
  },
  {
    title: "TextUtils - Perform operations on the text",
    projectImg: [
      "/assets/TextUtils/image1.png",
      "/assets/TextUtils/image2.png",
      "/assets/TextUtils/image3.png",
      "/assets/TextUtils/image4.png",
      "/assets/TextUtils/image5.png",
    ],
    video: "https://drive.google.com/file/d/1oQNc2vTlAg0vYWfxRm5O3oPHRqWxgXhO/preview",
    url: "https://makwana-dainik-kalabhai.github.io/TextUtils/",
    source: "https://github.com/Makwana-Dainik-Kalabhai/TextUtils",
    skills: ["React Js"],
    tech: "FrontEnd",
    techIcons: ["/assets/techImg/react.svg"],
  },
  {
    title: "Todo List - Add, Update & Delete Items/Tasks from the list",
    projectImg: [
      "/assets/TodoList/image1.png",
      "/assets/TodoList/image2.png",
      "/assets/TodoList/image3.png",
      "/assets/TodoList/image4.png",
      "/assets/TodoList/image5.png",
      "/assets/TodoList/image6.png",
    ],
    video: "https://drive.google.com/file/d/172XSokvuXU0ij-JlYH49v71CNxq60ccP/preview",
    url: "https://todo-list-dainik31.netlify.app/",
    source: "https://github.com/Makwana-Dainik-Kalabhai/itsTodo",
    skills: ["React Js"],
    tech: "FrontEnd",
    techIcons: ["/assets/techImg/react.svg"],
  },
  {
    title: "ImageGallery - Download Favourite Images",
    projectImg: [
      "/assets/ImageGallery/image1.png",
      "/assets/ImageGallery/image2.png",
      "/assets/ImageGallery/image3.png",
    ],
    video: "",
    url: "https://makwana-dainik-kalabhai.github.io/ImageGallery/",
    source: "https://github.com/Makwana-Dainik-Kalabhai/ImageGallery",
    skills: ["React Js"],
    tech: "FrontEnd",
    techIcons: ["/assets/techImg/react.svg"],
  },
  {
    title: "GALAXY HUB - Arcade Station",
    projectImg: [
      "/assets/GalaxyHub/image1.png",
      "/assets/GalaxyHub/image2.png",
      "/assets/GalaxyHub/image3.png",
      "/assets/GalaxyHub/image4.png",
      "/assets/GalaxyHub/image5.png",
    ],
    video: "https://drive.google.com/file/d/1X61qoxgIfa5szD4jMkIlqafpmGQdJOml/preview",
    url: "https://galaxy-hub-omega.vercel.app/",
    source: "https://github.com/Makwana-Dainik-Kalabhai/galaxy-hub",
    skills: ["React Js"],
    tech: "FrontEnd",
    techIcons: ["/assets/techImg/react.svg"],
  },
  {
    title: "ChitChat - Convert your thoughts into text",
    projectImg: [
      "/assets/ChitChat/image1.png",
      "/assets/ChitChat/image2.png",
      "/assets/ChitChat/image3.png",
      "/assets/ChitChat/image4.png",
      "/assets/ChitChat/image5.png",
    ],
    video: "https://drive.google.com/file/d/1MwTspV25E5hzGISZaoIZ-ATZEsoZSMzs/preview",
    url: "#",
    source: "https://github.com/Makwana-Dainik-Kalabhai/ChitChat",
    skills: ["React Js", "Express Js", "nodeJs", "mongoDB"],
    tech: "Full Stack",
    techIcons: [
      "/assets/techImg/react.svg",
      "/assets/techImg/express.svg",
      "/assets/techImg/nodejs.svg",
      "/assets/techImg/mongodb.svg",
    ],
  },
  {
    title: "Grease & Glory - Discover the Foods What You Loves",
    projectImg: [
      "/assets/GreaseGlory/image1.png",
      "/assets/GreaseGlory/image2.png",
      "/assets/GreaseGlory/image3.png",
      "/assets/GreaseGlory/image4.png",
      "/assets/GreaseGlory/image5.png",
      "/assets/GreaseGlory/image6.png",
      "/assets/GreaseGlory/image7.png",
      "/assets/GreaseGlory/image8.png",
      "/assets/GreaseGlory/image9.png",
      "/assets/GreaseGlory/image10.png",
      "/assets/GreaseGlory/image11.png",
    ],
    video: "https://drive.google.com/file/d/14UGIumPdGljW1sUg8nsyGRX1UEWNe0s3/preview",
    url: "#",
    source: "https://github.com/Makwana-Dainik-Kalabhai/Grease-Glory",
    skills: ["React Js", "Express Js", "nodeJs", "mongoDB"],
    tech: "Full Stack",
    techIcons: [
      "/assets/techImg/react.svg",
      "/assets/techImg/express.svg",
      "/assets/techImg/nodejs.svg",
      "/assets/techImg/mongodb.svg",
    ],
  },
  {
    title: "CampusFlow - Manage your Campus",
    projectImg: [
      "/assets/CampusFlow/image1.png",
      "/assets/CampusFlow/image2.png",
      "/assets/CampusFlow/image3.png",
      "/assets/CampusFlow/image4.png",
      "/assets/CampusFlow/image5.png",
      "/assets/CampusFlow/image6.png",
    ],
    video: "https://drive.google.com/file/d/1y9_yaUYXS92BDIKcZ5cO3dKQN4pH9ay3/preview",
    url: "#",
    source: "https://github.com/Makwana-Dainik-Kalabhai/clg-mgt-system",
    skills: ["React Js", "Express Js", "nodeJs", "mongoDB"],
    tech: "Full Stack",
    techIcons: [
      "/assets/techImg/react.svg",
      "/assets/techImg/express.svg",
      "/assets/techImg/nodejs.svg",
      "/assets/techImg/mongodb.svg",
    ],
  },
  {
    title: "Food Spoilage Detection - IOT based project",
    video:
      "https://drive.google.com/file/d/1Cu3xaBNZ6fwVpPovwzKYxu6_AbSTWA96/preview",
    projectImg: ["/assets/IOT.png"],
    url: "https://drive.google.com/file/d/1Cu3xaBNZ6fwVpPovwzKYxu6_AbSTWA96/view?usp=drive_link",
    source:
      "https://drive.google.com/drive/folders/16gOwFbdZaemk6XQnXBHujE5lfzl1wo0v?usp=sharing",
    skills: ["Python"],
    tech: "Internet of Things",
    techIcons: ["/assets/techImg/python.svg"],
  },
  {
    title: "CashFlow - Track Expenses, Save Smarter, Live Better",
    projectImg: [
      "/assets/CashFlow/image1.png",
      "/assets/CashFlow/image2.png",
      "/assets/CashFlow/image3.png",
      "/assets/CashFlow/image4.png",
      "/assets/CashFlow/image5.png",
      "/assets/CashFlow/image6.png",
      "/assets/CashFlow/image7.png",
    ],
    video: "https://drive.google.com/file/d/1BO4U_5o6UQiq7Wg9Imiam4lciDj5MFKK/preview",
    url: "#",
    source: "https://github.com/Makwana-Dainik-Kalabhai/CashFlow",
    skills: ["HTML", "CSS", "jQuery", "PHP", "MySQL"],
    tech: "Full Stack",
    techIcons: [
      "/assets/techImg/html.svg",
      "/assets/techImg/css.svg",
      "/assets/techImg/jquery.svg",
      "/assets/techImg/php.svg",
      "/assets/techImg/mysql.svg",
    ],
  },
  {
    title: "E-Commerce - Purchasing Medicines & Medical Devices",
    projectImg: [
      "/assets/E-Commerce/image1.png",
      "/assets/E-Commerce/image2.png",
      "/assets/E-Commerce/image3.png",
      "/assets/E-Commerce/image4.png",
      "/assets/E-Commerce/image5.png",
      "/assets/E-Commerce/image6.png",
      "/assets/E-Commerce/image7.png",
    ],
    video: "https://drive.google.com/file/d/1Cu3xaBNZ6fwVpPovwzKYxu6_AbSTWA96/preview",
    url: "#",
    source: "https://github.com/Makwana-Dainik-Kalabhai/Medicine_website",
    skills: ["HTML", "CSS", "jQuery", "PHP", "MySQL"],
    tech: "Full Stack",
    techIcons: [
      "/assets/techImg/html.svg",
      "/assets/techImg/css.svg",
      "/assets/techImg/jquery.svg",
      "/assets/techImg/php.svg",
      "/assets/techImg/mysql.svg",
    ],
  },
  {
    title: "GYM Mgt. System - Shape your body",
    projectImg: [
      "/assets/IFS/image1.png",
      "/assets/IFS/image2.png",
      "/assets/IFS/image3.png",
      "/assets/IFS/image4.png",
      "/assets/IFS/image5.png",
      "/assets/IFS/image6.png",
      "/assets/IFS/image7.png",
      "/assets/IFS/image8.png",
    ],
    video: "https://drive.google.com/file/d/1Cu3xaBNZ6fwVpPovwzKYxu6_AbSTWA96/preview",
    url: "#",
    source: "https://github.com/Makwana-Dainik-Kalabhai/IFS-Project",
    skills: ["HTML", "CSS", "jQuery", "PHP", "MySQL"],
    tech: "Full Stack",
    techIcons: [
      "/assets/techImg/html.svg",
      "/assets/techImg/css.svg",
      "/assets/techImg/jquery.svg",
      "/assets/techImg/php.svg",
      "/assets/techImg/mysql.svg",
    ],
  },
];

export const LANGUAGES = [
  {
    language: "HTML",
    icon: "/assets/techImg/html.svg",
  },
  {
    language: "CSS",
    icon: "/assets/techImg/css.svg",
  },
  {
    language: "Bootstrap",
    icon: "/assets/techImg/bootstrap.svg",
  },
  {
    language: "jQuery",
    icon: "/assets/techImg/jquery.svg",
  },
  {
    language: "React Js",
    icon: "/assets/techImg/react.svg",
  },
  {
    language: "C",
    icon: "/assets/techImg/c.svg",
  },
  {
    language: "C++",
    icon: "/assets/techImg/cpp.svg",
  },
  {
    language: "CoreJava",
    icon: "/assets/techImg/java.svg",
  },
  {
    language: "PHP",
    icon: "/assets/techImg/php.svg",
  },
  {
    language: "MySQL",
    icon: "/assets/techImg/mysql.svg",
  },
  {
    language: "nodejs",
    icon: "/assets/techImg/nodejs.svg",
  },
  {
    language: "mongoDB",
    icon: "/assets/techImg/mongodb.svg",
  },
  {
    language: "figma",
    icon: "/assets/techImg/figma.svg",
  },
  {
    language: "GitHub",
    icon: "/assets/techImg/github.svg",
  },
  {
    language: "VSCode",
    icon: "/assets/techImg/vs code.svg",
  },
];
